### ISSUE TITLE
未经处理的异常:  System.NullReferenceException: 未将对象引用设置到对象的实例。

### ISSUE THREAD

**Issue by cm-zl** [JDArmy/SharpXDecrypt#1]
![图片](https://user-images.githubusercontent.com/56428684/156090393-3bc9db6f-2050-4a47-84d5-67dbd977695f.png)

**Comment by 0pen1** [comment]
应该是“计算机\HKEY_CURRENT_USER\Software\NetSarang\Common\7\UserData”注册表项下面没有找到”UserDataPath“，已经添加异常捕获，感谢反馈！
