### ISSUE TITLE
密码乱码

### ISSUE THREAD

**Issue by handbye** [JDArmy/SharpXDecrypt#2]
xshell 7.1

![image](https://user-images.githubusercontent.com/26617058/163343720-d5a0ae68-a00c-4d62-af60-326fb1118d6d.png)

**Comment by mmioimm** [comment]
应该是sid 和user 不对吧，他这个需要目标机器的sid和user ，如果实在的自己电脑上，就得将目标机器的sid和user传入进去

**Comment by pynne** [comment]
同样问题，我是xshell 5.2 密码乱码。请问。sid 怎么找，哪里能获得。电脑从新安装了系统。

**Comment by shmilylty** [comment]
遇到同样的问题，是在目标机器上执行的，user和sid都是正确的。

**Comment by RookieTerry** [comment]
同样的问题，xshell7

**Comment by lxsgbin** [comment]
同意问题

**Comment by 0pen1** [comment]
有可能是执行程序的用户和使用xshell的用户不是同一个。没有太多信息也不好判断~
