### ISSUE TITLE
还是“未经处理的异常:  System.NullReferenceException: 未将对象引用设置到对象的实例。”

### ISSUE THREAD

**Issue by Fei123-design** [JDArmy/SharpXDecrypt#3]
![image](https://user-images.githubusercontent.com/61339141/218386136-20abf4ae-6039-4115-9c25-fbca97228acd.png)

**Comment by 0pen1** [comment]
注册表没有获取到路径

**Comment by 0pen1** [comment]
可以手动指定路径试试
